name: build-new

on:
  workflow_dispatch:
  push:
    branches: 
      - dev
      - tech/actions 
      - master
      - feature/implicit-tokens
  pull_request:
    branches: 
      - dev


permissions:
  pull-requests: write

jobs:
  publish:
    name: build, pack, test & publish
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
    steps:
      - uses: actions/checkout@main

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main

      - name: Restore, Build, test, and pack
        uses: Elskom/build-dotnet@main
        with:
          TEST: true
          PACK: true
    
