name: security
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
      - name: Setup .NET
        uses: actions/setup-dotnet@3.0.3
      - name: Restore dependencies
        run: dotnet restore ./path/to/your.sln
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
